#include "Modules/game.h"

/*DO NOT EDIT THIS FILE*/
/*
Welcome to Lock World, where there is a constant war between Demons and Humans.
Humans have no way of knowing the strength of the Demons, so many troops are
sacrificed to attack them, only to die in vain. The ongoing war is depleting the
kingdom's resources and causing poverty everywhere. Therefore, the ArchMages
decided to use a Summoning Circle to call forth a Hero from another world. From
this summoning, Budi was called from Earth to become the Hero. Budi was a former
overworked Computer Engineer who eventually collapsed and woke up in Lock World.
Budi decided to implement a system to simulate battles with Demons to determine
the minimum number of troops needed to kill one Demon. This simulation should
also be able to calculate if the number of troops used is within the kingdom's
budget. However Budi is NOT good with programming. Please help Budi to create
this simulation.
*/
int main() {
    runProgrammingLogic();
    return 0;
}